name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Sync Submodules
        run: git submodule sync
      - name: Configure Git
        run: |
          git config --global user.email "rokon.raz@gmail.com"
          git config --global user.name "RoknuzzamanRokon"
      - name: Update Submodules
        run: git submodule update --init --recursive
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Build Docker Image
        run: docker build -t rokondoc/demo-react .
      - name: Publish image to docker hub
        run: docker push rokondoc/demo-react:latest
