name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Configure Git
        run: |
          git config --global user.name "RoknuzzamanRokon"
          git config --global user.email "rokon.raz@gmail.com"
      - name: Update Submodules
        run: |
          git submodule sync
          git submodule update --init --recursive
      - name: Checkout Source
        uses: actions/checkout@v3
      - name: Debug Info
        run: |
          git --version
          git status
          git remote -v
          git branch -a
        continue-on-error: true
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Build Docker Image
        run: docker build -t rokondoc/demo-react .
      - name: Publish image to docker hub
        run: docker push rokondoc/demo-react:latest
